### ISSUE TITLE
MM generates extra "MaxItems" and "MiniItems"

### ISSUE THREAD

**Issue by neil-yechenwei** [VSChina/magic-modules#26]
"route_table": {
Type: schema.TypeList,
Computed: true,
Elem: &schema.Resource{
Schema: map[string]*schema.Schema{
"routes": {
Type: schema.TypeList,
Computed: true,
MinItems: ,
MaxItems: ,
Elem: &schema.Resource{
Schema: map[string]*schema.Schema{
"address_prefixes": {
Type: schema.TypeList,
Computed: true,
MinItems: ,
MaxItems: ,
Elem: &schema.Schema{
Type: schema.TypeString,
},
},
"next_hop_ip_address": {
Type: schema.TypeString,
Computed: true,
},
},
},
},
},
},
},

houkms: It's a problem in Magic-Modules and it was solved in MM-PR-18

**Comment by houkms** [comment]
It's a problem in Magic-Modules and it was solved in [MM-PR-18](https://github.com/VSChina/magic-modules/pull/18).

**Comment by mybayern1974** [comment]
@neil-yechenwei , would you please verify this fix and accordingly close this issue?

**Comment by houkms** [comment]
Closed due to no further response. @neil-yechenwei you can reopen the issue if  it's not completely solved.
