### ISSUE TITLE
MM doesn't support test case for deleting resource

### ISSUE THREAD

**Issue by neil-yechenwei** [VSChina/magic-modules#27]

**Comment by JunyiYi** [comment]
Hi @neil-yechenwei , what do you mean of "deleting resource"? All resources in Terraform tests will be removed automatically at the end of [`resource.ParallelTest`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_subnet_test.go#L22).

**Comment by houkms** [comment]
It seems we don't necessarily need this now.
