### ISSUE TITLE
[Feature Request] MM should handle errors when setting schema data and tags

### ISSUE THREAD

**Issue by ArcturusZhang** [VSChina/magic-modules#53]
For instance, in read function, currently mm will only generate the following code:
``` go
    d.Set("idle_timeout_in_minutes", natGatewayPropertiesFormat.IdleTimeoutInMinutes)
```
Ideally, this piece of code should be:
``` go
if err := d.Set("idle_timeout_in_minutes", natGatewayPropertiesFormat.IdleTimeoutInMinutes); err != nil {
    return fmt.Errorf("Error setting `idle_timeout_in_minutes`: %+v", err)
}
```

**Comment by HoukChen** [comment]
It seems that in Hashcorp's coding style, we only check errors when flatten functions are involved in `Set`. While in the above example, the field can be extracted directly.

Let's wait for more feedbacks from other reviewers about this situation.
