### ISSUE TITLE
MM don't need expand and flatten function when there is only one property

### ISSUE THREAD

**Issue by neil-yechenwei** [VSChina/magic-modules#58]
Current code:
![image](https://user-images.githubusercontent.com/19754191/66794414-07389f80-ef34-11e9-82f9-8de72f6a23b2.png)
![image](https://user-images.githubusercontent.com/19754191/66794436-13bcf800-ef34-11e9-99a9-553d93970ecd.png)
![image](https://user-images.githubusercontent.com/19754191/66794448-21727d80-ef34-11e9-8457-9146adbd1ac5.png)

Expect code:
![image](https://user-images.githubusercontent.com/19754191/66794455-2800f500-ef34-11e9-91ce-dbca85f13ad7.png)
![image](https://user-images.githubusercontent.com/19754191/66794456-2afbe580-ef34-11e9-9725-b763ddb1fc1f.png)

**Comment by houkms** [comment]
In this case, we can flatten the property. And that will be resolved in autorest.cli further.
