### ISSUE TITLE
MM should generate name of test case without word "Template"

### ISSUE THREAD

**Issue by neil-yechenwei** [VSChina/magic-modules#59]
Current Name: func testAccAzureRMPrivateLinkServiceTemplate_update(rInt int) string {
Expect Name: func testAccAzureRMPrivateLinkService_update(rInt int) string {

**Comment by magodo** [comment]
I'll take a look at this one

**Comment by magodo** [comment]
This issue can't be reproduced on latest MM(e2cd280), compiled against MM-spec (17aed40) , with related branches(7b345fd &  c5bd91f) merged (these two branches need to merge to complement MM-spec for private link).

Hence, close this issue.
