### ISSUE TITLE
Error occurs when a property is only as input for Read

### ISSUE THREAD

**Issue by houkms** [VSChina/magic-modules#84]
alertsmanagementsmartdetectoralertrule | package-2019-03

The property `expandDetector` is only a parameter of `Read.request` here.

**Comment by houkms** [comment]
Same issue when the property is only as input of other methods. For example, here

apimanagementapi | package-2017-03

`expandApiVersionSet` is only an input property for `list_by_parent`.

**Comment by magodo** [comment]
> alertsmanagementsmartdetectoralertrule | package-2019-03
> 
> The property `expandDetector` is only a parameter of `Read.request` here.

Tracked by #88

**Comment by magodo** [comment]
> Same issue when the property is only as input of other methods. For example, here
> 
> apimanagementapi | package-2017-03
> 
> `expandApiVersionSet` is only an input property for `list_by_parent`.

Tracked by #83
